### PR TITLE
warning for unused sections

### PR DESCRIPTION
**Pull request by tomasmcz**
This was meant to solve #319. However, there is a problem: when we run `neuralmonkey-test`, we intentionally supply it with a config that has unused sections. How do we solve this?

### CODE REVIEW

**Comment by jindrahelcl** [comment]
I think now, we can use `neuralmonkey-run` with exactly the same file as used in training.. The problem was, that the run script was loading the training data, which it did not use. This should no longer happen.

**Comment by jlibovicky** [comment]
I would check the config only for the train script. Typically, errors appear when you prepare the experiment, not when you want to run the trained model on test data.

**Comment by jindrahelcl** [comment]
jo jo, to by taky šlo.

**Comment by tomasmcz** [comment]
Teď by to mělo varovat jenom v trainu.

**Pull request merged**
