### PR TITLE
allow to set encoder.attention_matrix_size

### PR DESCRIPTION
**Pull request by obo**
Making the attention matrix larger reportedly helps. I have an experiment running, see TB on victoria:6016.

### CODE REVIEW

**Comment by jlibovicky** [comment]
I would suggest more general way of configuring attention. @jindrahelcl is going to write recurrent attention which have its own parameters, in the `multiencoder` branch, we are developing strategies of combining attentions and all the ad-hoc parameters of the attention types will become soon unmaintainable in this way.

What about having argument `attention_args` of type `List[Tuple[str, Any]]` in `Attentive`s' constructors? These arguments would be then passed to `attention_type`'s constructor in `create_attention_object` method.

**Comment by obo** [comment]
I have no idea what your plans are, so I'm open and looking forward to any other proposals. (Just a bit unpatient, as always ;-)

If you can modify my proposal so that it becomes one instance of your new generic setting, that would be great. If you have to dump it, well, go ahead :-/

----- Original Message -----
> From: "Jindřich Libovický" <notifications@github.com>
> To: "ufal/neuralmonkey" <neuralmonkey@noreply.github.com>
> Cc: "Ondrej Bojar" <bojar@ufal.mff.cuni.cz>, "Author" <author@noreply.github.com>
> Sent: Thursday, 26 January, 2017 01:06:10
> Subject: Re: [ufal/neuralmonkey] allow to set encoder.attention_matrix_size (#286)

> I would suggest more general way of configuring attention. @jindrahelcl is going
> to write recurrent attention which have its own parameters, in the
> `multiencoder` branch, we are developing strategies of combining attentions and
> all the ad-hoc parameters of the attention types will become soon
> unmaintainable in this way.
> 
> What about having argument `attention_args` of type `List[Tuple[str, Any]]` in
> `Attentive`s' constructors? These arguments would be then passed to
> `attention_type`'s constructor in `create_attention_object` method.
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ufal/neuralmonkey/pull/286#issuecomment-275272337

-- 
Ondrej Bojar (mailto:obo@cuni.cz / bojar@ufal.mff.cuni.cz)
http://www.cuni.cz/~obo

**Comment by jindrahelcl** [comment]
I actually need something exactly like this. But I agree we should do it more general.

When I look at it from the user view, I'd like the encoder configuration to look like this:

``` ini
[encoder]
class=encoders.sentence_encoder.SentenceEncoder
name="sentence_encoder"             
attention=<recurrent_attention>
; (...)

[recurrent_attention]
class=decoding_function.RecurrentAttention
state_size=200
; třeba i něco jako dropout_keep_prob=0.8
```

Doing this will be a slightly complicated by the fact that the attention objects are computing things in their constructors. It should be easy to solve, though.

The `__init__` method of the attention would just save the parameters. The encoders would call a `prepare` method, which would do computation that could be performed prior to the construction of the decoder. Then, decoders would call the `attention` method, which would remain unchanged.

**Comment by jindrahelcl** [comment]
Tohle jsme převzali a máme to hotový v branchi `multiencoder`, takže tenhle PR s dovolením zavřu. @jlibovicky  - tu branch bychom v brzký době měli vyčistit a udělat z ní pull request, než to chytne plíseň.

**Pull request closed without merging**
