### PR TITLE
Strict tests

### PR DESCRIPTION
**Pull request by tomasmcz**
This PR turns warnings into errors in tests.

Even if we decide not to use this, we should do something with the warning that it currently fails on. It's from `bpe.ini` and it says `The rnn_size argument is ignored in this type of projection.`. Apparently, it comes from the decoder. But there is no `rnn_size` for the decoder in the ini file. So it's not clear to me (as a user) what should I do to get rid of this warning.

### CODE REVIEW

**Comment by jindrahelcl** [comment]
The thing was, that the decoder computed its rnn_size prior calling the encoder projection, which does not need rnn_size. So instead warning, I added an assert inside the projection method to ensure it uses the correct rnn_size.

**Comment by tomasmcz** [comment]
OK. Next we have `small.ini` inferring vocabulary from lazy dataset.

**Comment by jindrahelcl** [comment]
I saved vocabularies from `vocab.ini` and reused them in `small.ini` so the dataset can remain lazy

**Comment by jindrahelcl** [comment]
in future, for the vocabulary creation, we should use something that could be called "fixtures"..

**Comment by jlibovicky** [comment]
Why do we actually have a warning while inferring vocabulary from lazy datasets? Because it's potentially slow?

**Comment by jindrahelcl** [comment]
Because you would generally prefer to load the vocabulary from a file and I believe that the fact that you are inferring it from lazy dataset should be emphasized, so I chose to do the emphasis by a warning.

**Pull request merged**
