### PR TITLE
Added condition for the variables config in run INI

### LINKED ISSUE #423: Variables for run script not checked
The `main.variables` config in dataset INI for running is not checked for type. So if you input a string, it takes its letters as paths to the variables.

### PR DESCRIPTION
**Pull request by jindrahelcl**
Closes #423

### CODE REVIEW

**Comment by jindrahelcl** [comment]
appprove pls

**Comment by varisd** [comment]
pls respond

**Comment by jindrahelcl** [comment]
to what?

**Comment by varisd** [comment]
your mom

**Pull request merged**
