### PR TITLE
Py35

### PR DESCRIPTION
**Pull request by tomasmcz**
I've run `2to3` on everything and now it fails with some interesting errors. We need to fix

- [x] pylint
- [x] tests
- [x] mypy

### CODE REVIEW

**Comment by tomasmcz** [comment]
Tests fail on `config_loader`. Can you fix that, @jlibovicky?

**Comment by jlibovicky** [comment]
I wish I could, but now I am not able to compile TF with python 3.5 on UFAL machines, so hopefully tomorrow. A least I updated the `prepare_env.sh` script.

One additional thing with python 3.5. All statements:

`import of regex as re`

should be replaced for just:

`import re`

**Comment by tomasmcz** [comment]
Why would you compile TF?

**Comment by tomasmcz** [comment]
@jlibovicky: There's no Python 3.5 at ÚFAL. Let's move to Python3.4 for now. I fixed your env script, it was full of errors anyway.  Now it's your turn to fix the config errors.

**Comment by jlibovicky** [comment]
Hm.. I still get:
`SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.`

**Comment by tomasmcz** [comment]
This means that with Python 3 we will not be able to run at ÚFAL cluster unless we persuade someone to install Python 3.5 with -dev or at least Python 3.4-dev. I don't really care, I can do debugging at home and experiments at Metacentrum.

**Comment by jlibovicky** [comment]
Btw., if you want to use the `prepare_env.sh` script at metacentrum, you have to download TF with wget first. pip can download only from pypi there. This is why it was in the script.

**Comment by jindrahelcl** [comment]
It is a high priority to be able run this on ufal's computers ( as concluded in #8 ). Should we contact Jindra V.?

**Comment by tomasmcz** [comment]
@jlibovicky: When you're writing such bizarre things, a comment with a reason wouldn't hurt. Also `set -ex` wouldn't hurt -- otherwise if this fails because there is no Python, it still downloads and deletes TF... Also, we have `<(wget ...)` in bash.

@jindrahelcl: Yes.

**Comment by jlibovicky** [comment]
We can use anaconda:
export PATH="/opt/python/anaconda3/bin:$PATH"
conda create --name py35 python=3.5

Sorry, I don't have time look at it closer. I will continue tomorrow.

**Comment by tomasmcz** [comment]
OK, anaconda works on ÚFAL, so we can go back to Python 3.5.

**Comment by tomasmcz** [comment]
@jlibovicky: You've broken this branch (even more than it is) by commiting parts of your Levenshtein and ansi refactors with the update to env_prepare.py.

**Comment by tomasmcz** [comment]
I fixed the errors and rebased it. The only problem is that the log prints everything like `b'text here...'`. Fix that and we can merge.

**Pull request merged**
