### PR TITLE
unify TF version across NM

### PR DESCRIPTION
**Pull request by tomasmcz**
Move Travis and requirements to TF 11.0.

I think it might also be good to mention the supported version (or versions?) of TF in the readme and documentation.

Currently there are 3 places that mention the TF version (`.travis.yml` and two requirement files). Would it be possible to somehow reduce them to one place to avoid inconsistent settings (as it was before this PR: we were telling users to install TF 10, but tests on Travis were running with TF 11.0rc0)?

### CODE REVIEW

**Comment by jindrahelcl** [comment]
As soon as the TF 0.12 is out (which is now, by the way), it will be the only supported version (because of the orthogonal initializers for recurrent weights).

**Comment by jindrahelcl** [comment]
- [ ] `tf.initialize_all_variables` is deprecated in tf 0.12

**Comment by tomasmcz** [comment]
Well, since TF 12.0 is only a release candidate and NM does not work with it yet, I'd like to merge this anyway.

This PR is about documenting and setting the TF version in NM, not about problems with particular version, so move TF 12 issues to #156, please.

**Comment by jindrahelcl** [comment]
Ok.

**Comment by jlibovicky** [comment]
I can't think of a way how to automate it. Maybe we can maintain a checklist telling what needs to be done if migrate to different version of TF.

**Comment by jindrahelcl** [comment]
We could use this github project's wiki for things like this, that we don't
want to put in user documentation.

2016-11-30 12:15 GMT+00:00 Jindřich Libovický <notifications@github.com>:

**Pull request merged**
