### PR TITLE
Fix a residual connection in TransformerDecoder

### PR DESCRIPTION
**Pull request by cifkao**

### CODE REVIEW

**Comment by jindrahelcl** [comment]
Did you try both settings and compare the results?

**Comment by varisd** [comment]
Imho, the comparison is not possible right now because we are still investigating the reasons why the transformer is not learning (this change alone is definitely not the core of the problem; but might be noticable with the working implementation).

**Comment by jindrahelcl** [comment]
I meant on the multimodal dataset, on which we have pretty good numbers already. That should not be unreproducible, I've sent you all the code pointers you need. Another thing is to make it learn on Czeng and I am not talking about that here.

**Comment by cifkao** [comment]
I re-ran your "pure_new_hope_lre-4_rebased" experiment with this change and I got a BLEU of 38.63; your result was 38.98 (both in epoch 8).

**Comment by jindrahelcl** [comment]
That seems reasonably comparable..

**Pull request merged**
