### PR TITLE
Best vars

### PR DESCRIPTION
**Pull request by tomasmcz**
Tests here are failing (see Travis log) due to #21, while in the current master they are OK. Can you fix this, @jindrahelcl?

### CODE REVIEW

**Comment by jindrahelcl** [comment]
The test data are so small the model is not saved and therefore there is no best variables file. Before this change, a randomly initialized model was saved at the beginning, which only took time and did nothing valuable. I will add a check after the training but I suggest to set the test configuration in the way the model would be validated (and therefore saved) at least once, to increase the test coverage.

**Comment by jindrahelcl** [comment]
The first part of what i wrote is not true. I don't know why it's failing.

**Comment by jindrahelcl** [comment]
I have a suspicion that this can be caused by travis and symlinks. Could you look into that @tomasmcz ? https://www.google.de/search?q=travis+symlinks&gws_rd=cr,ssl&ei=RT9xV8ypMcq_aLqRtugL

**Comment by tomasmcz** [comment]
@jindrahelcl, why are you adding commits from master onto this? Just rebase this on master.

This still fails on my local computer and I still find an incorrect symlink as described in #21. So this is not Travis fault. Checkout this branch and run `tests_run.sh` to replicate.

**Comment by jindrahelcl** [comment]
Fixed, tests are passing, now it works both with absolute and relative paths. Merging

**Pull request merged**
